plugins:

  - module: Input::Stdin

  - module: Parse::Common
    config:
        format: :extended

  - module: Parse::Normalize
    config: 
        time_zone: Asia/Tokyo

  - module: OutputLine::HadoopMap
#  
#  - module: Analyze::AccessCount
#
#  - module: Output::DBIC
#    config:
#        connect_info:
#            - dbi:mysql:test
